- name: clean daq machine from the old services
  hosts: '{{ host }}'
  become: true
  tasks:
    - name: stop, disable and remove services
      shell: |
          systemctl stop jungfrau*
          rm -rf /etc/systemd/system/multi-user.target.wants/jungfrau*
          rm -rf /etc/systemd/system/jungfrau*
          rm -rf /home/dbe/git /home/dbe/miniconda3 /home/dbe/service_scripts /home/dbe/swissfel

          
  

