
- name: install receiver services on daq3 for JF01
  hosts: sf_daq_bernina
  become: true

  vars:
      detector: JF01
      detector_full_name: JF01T03V01
      visualisation_cores: 17,18
      visualisation_view: bernina
      alias_visualisation: sf-daq-bernina
      incoming_data_port: 9001
      visualisation_port: 5001
      visualisation_title: 1p5M
      stream_cores: 24
      stream_config: stream-{{ detector }}.json
      last_module_number: 02
      cores_receivers: 12 12 12
      initial_udp_port: 50010

  tasks:
    - name: install visualisation script for detector
      become_user: dbe
      template:
          src: templates/streamvis.sh
          dest: /home/dbe/service_scripts/{{ detector }}-vis.sh

    - name: install stream script for detector
      become_user: dbe
      template:
          src: templates/stream.sh
          dest: /home/dbe/service_scripts/{{ detector }}-stream.sh

    - name: install buffer script for detector
      become_user: dbe
      template:
          src: templates/buffer-worker.sh
          dest: /home/dbe/service_scripts/{{ detector }}-buffer-worker.sh

    - name: install service files for all services
      become_user: root
      template: src={{item.src}} dest={{item.dest}}
      with_items:
      - { src: 'templates/buffer.service',        dest: '/etc/systemd/system/{{ detector }}-buffer.service' }
      - { src: 'templates/buffer-worker.service', dest: '/etc/systemd/system/{{ detector }}-buffer-worker@.service' }
      - { src: 'templates/stream.service',        dest: '/etc/systemd/system/{{ detector }}-stream.service' }
      - { src: 'templates/streamvis.service',     dest: '/etc/systemd/system/{{ detector }}-vis.service' }

    - name: start detector services
      systemd: state=started name={{item.name}} daemon_reload=yes
      with_items:
      - { name: '{{ detector }}-buffer' }
      - { name: '{{ detector }}-stream' }
      - { name: '{{ detector }}-vis' }

