
- name: install receiver services on daq9 for JF04T01V01
  hosts: sf_daq_maloja
  become: true

  vars:
      detector: "{{ JF04_detector_short_name }}"
      detector_full_name: "{{ JF04_detector_full_name }}"
      visualisation_view: "{{ JF04_visualisation_view }}"
      visualisation_incoming_data_port: "{{ JF04_visualisation_incoming_data_port }}"
      visualisation_port: "{{ JF04_visualisation_port }}"
      visualisation_title: "{{ JF04_visualisation_title }}"
      last_module_number: "{{ JF04_last_module_number }}"
      initial_udp_port: "{{ JF04_initial_udp_port }}"

      stream_config: stream-{{ detector }}.json
      visualisation_alias: sf-daq-maloja
      visualisation_cores: 3
      stream_cores: 4
      cores_receivers: 5

  tasks:
    - name: install visualisation script for detector
      become_user: dbe
      template:
          src: templates/streamvis.sh
          dest: /home/dbe/service_scripts/{{ detector }}-vis.sh

    - name: install stream script for detector
      become_user: dbe
      template:
          src: templates/stream.sh
          dest: /home/dbe/service_scripts/{{ detector }}-stream.sh

    - name: install buffer script for detector
      become_user: dbe
      template:
          src: templates/buffer-worker.sh
          dest: /home/dbe/service_scripts/{{ detector }}-buffer-worker.sh

    - name: install service files for all services
      become_user: root
      template: src={{item.src}} dest={{item.dest}}
      with_items:
      - { src: 'templates/buffer.service',        dest: '/etc/systemd/system/{{ detector }}-buffer.service' }
      - { src: 'templates/buffer-worker.service', dest: '/etc/systemd/system/{{ detector }}-buffer-worker@.service' }
      - { src: 'templates/stream.service',        dest: '/etc/systemd/system/{{ detector }}-stream.service' }
      - { src: 'templates/streamvis.service',     dest: '/etc/systemd/system/{{ detector }}-vis.service' }

    - name: start detector services
      systemd: state=started name={{item.name}} daemon_reload=yes
      with_items:
      - { name: '{{ detector }}-buffer' }
      - { name: '{{ detector }}-stream' }
      - { name: '{{ detector }}-vis' }

