package:
    name: sf_daq_broker
    version: 0.0.1

source:
    path: ..

requirements:
    build:
        - python

    run:
        - python
        - bottle
        - requests
        - data_api
        - pika
        - pyepics

build:
  number: 0
  entry_points:
    - sf_daq_broker = sf_daq_broker.broker:run
    - sf_daq_broker_writer = sf_daq_broker.writer.start:run

about:
    home: https://github.com/paulscherrerinstitute/sf_daq_broker
